language: go
go:
 - 1.6.1
 - tip
 - 1.7.1

install:
 - make install

before_script:
 - make

script:
 - go test -v -cover ./...

after_script:
 - make clean
 - make errcheck
notifications:
  email: false
